[package]
name = "test_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.9.5"
reqwest = "0.11"
tokio = { version = "1", features = ["full"] }
